apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datacharter.fullname" . }}
  labels:
    {{- include "datacharter.labels" . | nindent 4 }}
data:
  charter.yaml: |
    {{- .Values.charter | nindent 4 }}
