"""Governed synthetic data: generate realistic-looking rows that match a relation's
schema and honor the contract's PII declarations.

Dev, test, and CI need data shaped like production but must never hold the real
rows. Because the generator reads the *same* charter that guards prod, a PII column
comes out as a clearly-synthetic stand-in (never a real value), and the schema
contract is preserved. The same policy that protects prod shapes the fixtures.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

__all__ = ["Column", "synth_value", "synthesize"]

_FIRST = ["Ada", "Bo", "Cy", "Di", "Eve", "Fen", "Gil", "Hana", "Ivo", "Jo",
          "Kit", "Lux", "Mira", "Nero", "Ola", "Pax", "Quin", "Ravi", "Sol", "Uma"]
_LAST = ["Ash", "Bell", "Crane", "Dune", "Ellis", "Frost", "Gray", "Holt", "Iver",
         "Jung", "Kerr", "Lowe", "Marsh", "North", "Oke", "Pike", "Reed", "Stone"]
_CITY = ["Ferrytown", "Northgate", "Elmshire", "Bay City", "Redhollow", "Westmoor"]
_DOMAINS = ["example.com", "example.org", "test.invalid"]


@dataclass(frozen=True)
class Column:
    name: str
    type: str
    is_pii: bool = False


def _num_type(t: str) -> str:
    t = t.upper()
    if any(k in t for k in ("INT", "HUGEINT")):
        return "int"
    if any(k in t for k in ("DOUBLE", "REAL", "FLOAT", "DECIMAL", "NUMERIC")):
        return "float"
    if "BOOL" in t:
        return "bool"
    if "TIMESTAMP" in t or "DATETIME" in t:
        return "timestamp"
    if "DATE" in t:
        return "date"
    return "text"


def _fake_email(rng: random.Random) -> str:
    return f"user{rng.randint(1000, 9999)}@{rng.choice(_DOMAINS)}"


def _fake_phone(rng: random.Random) -> str:
    # 555-01xx is the reserved fictional exchange — unmistakably not a real number.
    return f"+1-555-01{rng.randint(0, 99):02d}"


def synth_value(col: Column, rng: random.Random, row_i: int):
    """One synthetic cell. PII columns get shape-preserving, obviously-fake values;
    other columns are generated by name heuristic then falling back to type."""
    name = col.name.lower()
    kind = _num_type(col.type)

    # PII columns always get a clearly-synthetic stand-in of the right shape.
    if col.is_pii:
        if "email" in name:
            return _fake_email(rng)
        if "phone" in name:
            return _fake_phone(rng)
        if "ssn" in name:
            return f"000-00-{rng.randint(0, 9999):04d}"
        if "name" in name:
            return f"{rng.choice(_FIRST)} {rng.choice(_LAST)}"
        if kind == "text":
            return f"redacted-{rng.randint(1000, 9999)}"

    if kind == "int":
        return row_i + 1 if name in ("id", "pk", "rowid") else rng.randint(1, 100000)
    if kind == "float":
        return round(rng.uniform(1, 10000), 2)
    if kind == "bool":
        return rng.random() < 0.5
    if kind == "date":
        return f"20{rng.randint(20, 25):02d}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}"
    if kind == "timestamp":
        return (f"20{rng.randint(20, 25):02d}-{rng.randint(1, 12):02d}-"
                f"{rng.randint(1, 28):02d} {rng.randint(0, 23):02d}:{rng.randint(0, 59):02d}:00")

    # Text, by name heuristic.
    if "email" in name:
        return _fake_email(rng)
    if "phone" in name:
        return _fake_phone(rng)
    if "name" in name:
        return f"{rng.choice(_FIRST)} {rng.choice(_LAST)}"
    if "city" in name:
        return rng.choice(_CITY)
    if any(k in name for k in ("tier", "plan", "status", "type", "category")):
        return rng.choice(["free", "pro", "enterprise"])
    return f"{name}-{rng.randint(1000, 9999)}"


def synthesize(columns: list[Column], n: int, seed: int | None = None) -> list[list]:
    """Generate `n` rows for the schema. `seed` makes the output reproducible."""
    rng = random.Random(seed)
    return [[synth_value(c, rng, i) for c in columns] for i in range(n)]
